apiVersion: v1
kind: Pod
metadata:
  generateName: copy-
spec:
  containers:
  - name: main
    image: ubuntu:18.04
    command: ["sleep", "1000000000"]
    volumeMounts:
    - name: pollux
      mountPath: /pollux/checkpoint
      subPath: pollux/checkpoint/
  volumes:
  - name: pollux
    persistentVolumeClaim:
      claimName: pollux
