apiVersion: v1
kind: ServiceAccount
metadata:
  name: adaptdl
  namespace: {{.Release.Namespace}}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
