apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-global-profiler
  labels:
    app: adaptdl-sched
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.globalProfiler.service.port }}
      targetPort: {{ .Values.globalProfiler.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: adaptdl-sched
    release: {{ .Release.Name }} 