apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: adaptdl-eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: 12xlargeonlycifar
    instanceTypes: ["g4dn.12xlarge"]
    desiredCapacity: 0
    minSize: 0
    maxSize: 4

    # <-- your snapshot AMI here
    amiFamily: AmazonLinux2
    ami: ami-0c9cffa5d7ae29949

    # required when you set a custom AMI for AL2
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh adaptdl-eks-cluster
