apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: deepspeech2-
spec:
  template:
    spec:
      containers:
      - name: main
        command:
        - python
        - /root/deepspeech2/train.py
        - --cuda
        - --train-manifest=/root/deepspeech2/voxforge_train_manifest.csv
        - --val-manifest=/root/deepspeech2/voxforge_val_manifest.csv
        - --max-norm=1
        - --batch-size=20
        - --lr=0.12
        - --learning-anneal=1.02
        - --momentum=0.95
        - --epochs=80
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 1
            memory: "12G"
          requests:
            nvidia.com/gpu: 1
            cpu: 1
            memory: "12G"
      imagePullSecrets:
      - name: regcred
